name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: Javilone/Javilone@v1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIMETOKEN }}
          GH_TOKEN: ${{ secrets.GITHUBPERSONALACCESS }}
